#%RAML 1.0 NamedExample
value:

  -
    ID: 1
    size: M
    color: Blue
    printed: True
    sleeve: Long
  -
    ID: 2
    size: PP
    color: Pink
    printed: False
    sleeve: Short
  -
    ID: 3
    size: GG
    color: Black
    printed: False
    sleeve: Tank Top